### ISSUE TITLE
link to Tekton in downloads page

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-website#25]
in /download we should find the right links to Tekton. The readme sounds like the only place so far that would make sense to link to https://github.com/tektoncd/pipeline

see if other links are good to add in the readme

**Comment by marikaj123** [comment]
Assignee: Melissa

**Comment by marikaj123** [comment]
Melissa suggested closing this since this functionality will be replaced by Getting started page.

**Comment by ralanlittle** [comment]
Tekton is not something that will be downloaded or exposed directly to Jane, Champ, and Todd installs it via the Kabanero operator.  Tekton should be considered an internal detail,  and only Champ will deal with Tekton in the creation or modification of pipelines, not the actual download or install of Tekton.

**Comment by mdenby** [comment]
It looks like Tekton is surfaced as part of Todd setting up Kabanero Foundation--https://github.com/kabanero-io/docs/blob/master/ref/general/kabanero-foundation-setup.adoc

and aside from mentioning on the Homepage and Getting Started page as something to setup for Foundation it seems like the instructions and links etc are on the GitHub page. I also believe we talk more about Tekton in the Foundation/OKD pages when Champ will need to set it up.

Since we don't have a downloads page--can we close this issue?
