### ISSUE TITLE
Slack icon hasn't updated

### ISSUE THREAD

**Issue by DunnCoding** [kabanero-io/kabanero-website#294]
#### Describe the bug
Slack icon is still the old icon, only now it's bigger. Also the slack icon in the footer has lost its alignment and disappears when you hover over it. 

#### Expected behavior
New Slack icon same size as the other social icons.  

#### Screenshots
<img width="401" alt="Screenshot 2019-11-18 at 10 53 23" src="https://user-images.githubusercontent.com/25609923/69046783-b8c66700-09f1-11ea-9d44-dbf9ede5b4ab.png">

**Comment by alohr51** [comment]
@ddunn2 That is a browser cache issue, please do a hard reload on your browser.

**Comment by DunnCoding** [comment]
Ah yes, you're right after doing that the new logos appeared. 

However the logo in the footer still seems to disappear when you hover over it.

**Comment by alohr51** [comment]
thanks @ddunn2 ! I see that too, we'll use this issue to fix that

**Comment by kSee04** [comment]
I see the issue on `kabanero.io` but it's already fixed in master.  On `kabanero.io`, the file name for the Slack hover logo `/img/slack_Icon_hover.svg` is capitalized differently than the value of the `background-image` css rule `/img/slack_Icon_Hover.svg`. This difference is already fixed on master.

Here's a screenshot of the issue on `kabanero.io`:
![Screen Shot 2019-11-19 at 10 12 04 AM](https://user-images.githubusercontent.com/37549026/69158944-26879700-0ab5-11ea-8a36-093c0256212a.png)

Here's a screenshot of master where the link is fixed: 
![Screen Shot 2019-11-19 at 10 12 13 AM](https://user-images.githubusercontent.com/37549026/69158976-356e4980-0ab5-11ea-96d6-1617a02c00bd.png)

@alohr51 should we just close this issue, then? Looks we already fixed it and it's just not deployed.

**Comment by alohr51** [comment]
thanks for checking @kSee04 !
