### ISSUE TITLE
Clean up Kabanero collection terminology on kabanero.io

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-website#335]
#### Feature description

Kabanero Collection -> Application Stack
Kabanero Collection Hub -> Stack Hub
Kabanero Collection CLI -> Stack CLI

**Comment by SueChaplain** [comment]
@alohr51 

My understanding, based on input from Nate:

Kabanero Collection ..... we talk about application stacks
Appsody stacks -> Application stacks
Tekton Pipelines -> pipelines
Collection hub -> stack hub

As part of this work, please can you change the Guides category displayed on the site from "Collections" to "Stacks". If you change the underlying category, please let me know so that we can make the corresponding change in the guide source.

**Comment by marikaj123** [comment]
PR is currently under review https://github.com/kabanero-io/kabanero-website/pull/353
