### ISSUE TITLE
Software needed for the trial link

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-website#37]
We want to make codewind and appsody available. Andrew already has a link foor downloads on the staging system.  
![2](https://user-images.githubusercontent.com/5471755/61142160-18899000-a49d-11e9-8f6a-73f9e3731875.png)

Please change from Downloads to "Try-it",  remove tabs for Kabanero, and Tekton.  

Under the tab for Codewind,  add the text right above the link.

Codewind provides the technology that plugs into customers IDEs, that allows container based applications to be build.  

The link should be point to https:\\codewind.dev not our internal site.

Under the appsody tab, add a similar Structure as for codewind,  but use this text and a link to Https://appsody.dev

Infused with cloud native capabilities from the moment you start, Appsody provides everything you need to iteratively develop applications.

**Comment by nateziemann** [comment]
I rewrote this page, see the word doc attached.  I've attached the two logos I'd like to include in the tabs too.
![Logo icon](https://user-images.githubusercontent.com/28736793/61259008-df237f80-a73d-11e9-93a8-257d9020b4b2.png)
![Codewind_blue@64px](https://user-images.githubusercontent.com/28736793/61259014-e3e83380-a73d-11e9-978d-0aee5ad21dfe.png)

**Comment by nateziemann** [comment]
[Try It page.docx](https://github.com/kabanero-io/kabanero-website/files/3394800/Try.It.page.docx)

**Comment by GeoffPirie** [comment]
I made a few changes to the opening paragraph, to speak more directly to the developer audience, and to suggest that they shouldn't be wasting time doing infrastructure work.  

I think we should drop the sentence about moving from legacy infrastructure because (a) I think it's talking about developers, not to them, (b) I think it runs the risk of feeling tied to the past.

If we still want to include a legacy message, can it be in the closing paragraph instead?  This still allows SEO to pick up on the keyword, but doesn't make it a top-level message that might put some people off.

Both new and old content on separate pages in this version of the Doc:
[Try.It.page-16July.docx](https://github.com/kabanero-io/kabanero-website/files/3396257/Try.It.page-16July.docx)

**Comment by nateziemann** [comment]
I also got feedback from the architects on which steps are really required.  So I merged Geoff's feedback with the architects.  Here's the result.
[Try.It.page-v3.docx](https://github.com/kabanero-io/kabanero-website/files/3396880/Try.It.page-v3.docx)
